### ISSUE TITLE
Generated app still uses React logo

### ISSUE THREAD

**Issue by nilz3ro** [infernojs/create-inferno-app#10]
When you generate an app, there is an animated React logo, we should probably replace this with an Inferno logo and also add an Inferno favicon.

**Comment by Havunen** [comment]
We should definitely make it look and behave more like Inferno. Is this something you could contribute on? Pull requests are welcome :)

**Comment by nilz3ro** [comment]
@Havunen Yes, no problem. @trueadm Who can add me to the organization on npm for create-inferno-app so I can publish?

**Comment by Havunen** [comment]
Currently I think only me, nightwolfz and trueadm has rights to publish. But you can push to repo and when its good to go just ping one of us. I believe we will add more people with rights soon in future if needed

**Comment by trueadm** [comment]
@nilz3ro I've add you to have NPM powers too so you can help on create inferno app :)

**Comment by nilz3ro** [comment]
@trueadm cool ✨  I'll use them quite responsibly, I only ask because sometimes it's easier to debug dependency issues with a test release.

**Comment by Havunen** [comment]
Fixed. Template now uses Inferno color theme + logo etc.
