### ISSUE TITLE
Publish new version with Inferno 1.0.0-beta35

### ISSUE THREAD

**Issue by trueadm** [infernojs/create-inferno-app#11]
@nilz3ro

I've updated the version of Inferno to use (`@beta34`). Would you mind checking it over and doing a release if looks okay to you?

**Comment by nilz3ro** [comment]
@trueadm Yes, I can review and publish this evening. I'm in the U.S. East timezone.

**Comment by Havunen** [comment]
Fixed. latest version uses latest babel plugin 1.3.0-beta15 and inferno36.
