### ISSUE TITLE
Recompile CSS files within subdirs

### ISSUE THREAD

**Issue by lukeed** [infernojs/create-inferno-app#12]
### Description

Watcher does not trigger recompile on sub-level `.css` changes.

```
src
|- index.js
|- index.css
|- App.css
|- App.js
  \components
   | - Sidebar.js
   | - Sidebar.css
```

Saving `src/components/Sidebar.css` should trigger the same behaviors as saving `src/App.css`.

---

Easy fix. I just don't have time to right now.

**Comment by Havunen** [comment]
I cannot reproduce this. Note that if you have not imported Sidebar from App.js it doesn't trigger. It doesn't trigger recompile if it doesn't change output. Steps to reproduce needed.
