### ISSUE TITLE
server side rendering

### ISSUE THREAD

**Issue by flieks** [infernojs/create-inferno-app#16]
The scripts are working great but how to do server side rendering with them?
I'm using firebase

Thanks in advance

**Comment by Havunen** [comment]
I'm not familiar with SSR using Inferno or React, but I think you can find many skilled developers in that area from our slack. Feel free to join and ask questions there. 

link: https://inferno-slack.herokuapp.com/

**Comment by Havunen** [comment]
There are many tutorials how to SSR nowdays. Just check out one of the tutorials made for React. Same practices apply to Inferno
