### ISSUE TITLE
Babel config for JSX not working

### ISSUE THREAD

**Issue by hulkish** [infernojs/create-inferno-app#18]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Can you reproduce the problem with latest npm?

Yes, I'm running `npm@4.0.5` and I've ran this: (im  on OSX)
```
npm install -g npm@latest

cd your_project_directory
rm -rf node_modules
npm install
```

### Can you still reproduce it? 

Yes

### Description

*in-browser* runtime errors related to jsx not being compiled via babel:

```
5.2f3d2e1….chunk.js:1 Uncaught SyntaxError: Unexpected token <
main.fa8c7ab….js:1 Dynamic page loading failed Error: Loading chunk 5 failed.
    at HTMLScriptElement.n (main.fa8c7ab….js:1)
i @ main.fa8c7ab….js:1
1.fea1997….chunk.js:1 Uncaught SyntaxError: Unexpected token <
0.c1522f9….chunk.js:1 Uncaught SyntaxError: Unexpected token <
main.fa8c7ab….js:1 Uncaught (in promise) Error: Loading chunk 5 failed.
    at HTMLScriptElement.n (main.fa8c7ab….js:1)
n @ main.fa8c7ab….js:1
sw.js:1 The script has an unsupported MIME type ('text/html').
http://localhost:3000/sw.js Failed to load resource: net::ERR_INSECURE_RESPONSE
```

### Expected behavior

App should run.

### Actual behavior

Blank page with errors in console

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls inferno-scripts` (if you haven’t ejected): 
```sh
$ npm ls inferno-scripts
inferno-test-2@0.1.0 /Users/<home>/dev/repos/inferno-test-2
└── inferno-scripts@0.10.2
```
2. `node -v`:  v7.3.0
3. `npm -v`: 4.0.5

Then, specify:

1. Operating system: `OSX macOS Sierra v10.12.2`
2. Browser and version: `Chrome v55.0.2883.95`

### Reproducible Demo

https://github.com/hulkish/inferno-test-2

**Comment by Havunen** [comment]
Hey @hulkish what should I do to reproduce the issue in your github repository?

What I tried so far:
I clone the repository.
I did `npm i`
I ran `npm run start` -> browser opened localhost:3000   (basic example renderd, no errors in console)
I ran `npm run build` I got info that production build was successfully made

**Comment by hulkish** [comment]
@Havunen For me,  I just run:

```
npm install
npm start
```

No errors during build and it seems like its working -  however in the browser is where the error occurs

... what version of node are u using? i wonder if its. because of the version im using

**Comment by hulkish** [comment]
I just tried this again with a different version of node (`6.9.3`) and got the same (error'd behavior as I originally reported)

**Comment by Havunen** [comment]
I previously tried with nodeJS 7.3.0  and npm 4.0.5 on my linux stack. I will try with windows machine nodeJS 7.4.0 now.

**Comment by Havunen** [comment]
What I have tried so far:

```
git clone https://github.com/hulkish/inferno-test-2.git
npm install (wait until its ready)
npm start
- open Google Chrome v55 64bit  localhost:3000 (no errors in console)
- open FireFox v50.1.0  localhost:3000 (no errors in console)
- open Microsoft EdgeHTML 14.14393  localhost:3000 (no errors in console)
- open Internet Explorer 11.576  localhost:3000 (no errors in console)

npm test (test runner starts 1 test pass)
I tried editing Inferno text in source and it reflect into the browser also. (hot reloading)

npm -v 4.0.5
node -v 7.4.0 
windows 10 build 1607
```

I have also tried to reproduce this on my Linux stack no luck... what am I doing wrong?

**Comment by Havunen** [comment]
I started browsing upstream repository and do you think any of these is related?: 
https://github.com/facebookincubator/create-react-app/issues/658

Also now when I'm reading your description I noticed this line: 
sw.js:1 The script has an unsupported MIME type ('text/html').
http://localhost:3000/sw.js Failed to load resource: net::ERR_INSECURE_RESPONSE

but I don't see sw.js anywhere loaded

**Comment by lukeed** [comment]
You likely have a service worker still running from a previous project. Clear service workers from within chrome devtools (application > service workers) and then hard reload the page.

This happens to me every once in a while.

**Comment by hulkish** [comment]
@lukeed yep, that was it! That is a pretty sneaky one.. will definitely be making note of that lol

**Comment by LukeSheard** [comment]
Closing this then. 👍
