### ISSUE TITLE
Modify `eject` survey message or URL

### ISSUE THREAD

**Issue by dfrankland** [infernojs/create-inferno-app#19]
After running `npm run eject` the user has the following message displayed:

```text
Please consider sharing why you ejected in this survey:
  http://goo.gl/forms/Bi6CZjk1EqsdelXk1
```

This leads to Facebook's `create-react-app` survey, not Inferno's `create-inferno-app` survey. Perhaps we should remove or create our own survey?

For reference, the line that would need to be changed is here:
https://github.com/infernojs/create-inferno-app/blob/master/packages/inferno-scripts/scripts/eject.js#L159

**Comment by Havunen** [comment]
This seems to be valid issue, I don't know how to create our own survey. Is this something you could do?

**Comment by dfrankland** [comment]
I've copied the survey that React had created and replace "React" with "Inferno". Here's the link: https://goo.gl/forms/8ZQVOOtZssa71NZN2

This can replace the current survey, but I would need to add people as collaborators for them to see the results.

**Comment by Havunen** [comment]
I removed the eject survey. If anybody has issues its better to open issue here, following multiple places is difficult and time consuming.
