### ISSUE TITLE
[Feature Request] Add typescript support to create-inferno-app. 

### ISSUE THREAD

**Issue by dessalines** [infernojs/create-inferno-app#20]
I've found the https://github.com/infernojs/inferno-typescript-example project, but it would be really nice to add typescript and tsx support to this build system. It could be a command line parameter, that makes a typescript project instead, or simply support .ts files and transpile them when necessary.

**Comment by Havunen** [comment]
Hey

I have converted the linked repository to use TSX. Please continue discussion regarding that there.

**Comment by cedvdb** [comment]
so any info on this ? I'd like to use typescript with inferno

**Comment by Havunen** [comment]
no babel https://github.com/infernojs/inferno/issues/1154
babel https://github.com/infernojs/inferno-typescript-example
