### ISSUE TITLE
Yarn stuck

### ISSUE THREAD

**Issue by Tseberechts** [infernojs/create-inferno-app#21]
### Can you reproduce the problem with latest npm?

Yes, npm -v: 4.0.5

### Description

Yarn gets stuck on Installing Inferno-scripts. Currently stuck on: esprima@~3.0.0

### Expected behavior

Yarn should install the Inferno-scripts

### Actual behavior

Yarn gets stuck on esprima@~3.0.0

### Environment

1. `npm ls inferno-scripts` (if you haven’t ejected): `-- (empty)
2. `node -v`: 7.4.0
3. `npm -v`: 4.0.5
4. `yarn version`: 0.18.1

Then, specify:

1. Operating system: Windows 7 Professional x64
2. Browser and version: /

### Reproducible Demo

* npm install -g create-inferno-app
* create-inferno-app my-app

**Comment by Tseberechts** [comment]
Also regularly gets stuck on spdx-license-ides@1.0.2

**Comment by trueadm** [comment]
@Tseberechts I had the same issues yesterday but they seem to be fine today after clearing my cache. It might been a network issue with NPM or your local cache?

**Comment by Tseberechts** [comment]
cleaned npm and yarn cache. no luck

**Comment by trueadm** [comment]
@Tseberechts could it be a network issue, can you try with a different network? Also does Create React App work fine for you?

**Comment by Tseberechts** [comment]
- I can't try with a different network as I'm at work. 
- Create-react-app works, but only after a few tries

**Comment by trueadm** [comment]
@Tseberechts I'm not sure what else to say – I've just retried it now and it works fine here. I'm not sure if this issue is related to Windows, I'm on a Mac and don't have a PC to test on. @Havunen can you try on Windows?

**Comment by Havunen** [comment]
Tested on Microsoft Windows [Version 10.0.14393]   Node 7.4.0  npm 4.0.5 all seems to work. This needs more info.

**Comment by Havunen** [comment]
I merged upstream today and there were couple changes to yarn I think those fixed this issue. If not re-open please. Closing.
