### ISSUE TITLE
Webpack 2.0

### ISSUE THREAD

**Issue by dbismut** [infernojs/create-inferno-app#23]
Hey - I'm really interested in this, congrats! I've seen that create-react-app is now using webpack 2.0, any plans of doing the same? Just curious, it's not vital considering one of the main objectives of this bootstrap is to *not* care about webpack configuration...

**Comment by lukeed** [comment]
I'm sure that it can be imported easily, or even rebased from the react version. You're welcome to PR too :) 

If you just want to get started with something simpler, you can have a look at my [`inferno-starter`](https://github.com/lukeed/inferno-starter). It's built with Webpack2 but doesn't have all the auto-generation that this repo has.

**Comment by dbismut** [comment]
Hehe don't know if I'm a good candidate for a PR, don't know much about webpack.

**Comment by Havunen** [comment]
React version is still using webpack v1. Let's wait till they upgrade and then follow. This package has quite complex scripts written for webpack.

**Comment by Rayraegah** [comment]
@lukeed I actually turned your nice starter into a [vue-cli template](https://github.com/Rayraegah/inferno-starter) 📦

**Comment by sebastianrothe** [comment]
The React team recently switched their code https://github.com/facebookincubator/create-react-app/pull/1291

**Comment by degroote22** [comment]
@sebastianrothe They've switched it only on their master branch. The latest release is still using webpack1. I guess we should wait for the official release to make the transition here.

**Comment by sebastianrothe** [comment]
Oh, sorry you are right.

**Comment by Havunen** [comment]
New version has been released today with Inferno 1.3.0 and Webpack 2. Also all changes from upstream has been merged.
