### ISSUE TITLE
SVG xlink:href NOT WORKING raising "TypeError: name.toLowerCase is not a function"

### ISSUE THREAD

**Issue by unbewusst** [infernojs/create-inferno-app#24]
within react, when including an svg "symbol", I've used "xlinkHref" translated to "xlink:href" after transpiling.
this doesn't work within Inferno;
I've found a working solution for the latest Firefox : using simply href, however this doesn't work with other browser, for example Safari Tech Prev.
Is there anyway to use straight "xlink:href" without this error :
Failed to compile.

Error in ./src/ItemView.js
Module build failed: TypeError: name.toLowerCase is not a function
   at Array.forEach (native)

**Comment by wasd171** [comment]
I suppose it is a problem with Inferno dehyphenizing algorithm itself, let me take a look

**Comment by wasd171** [comment]
@unbewusst I think I found the reason. Until an updated version is published, could you try just write `xlink:href` and see whether it works for you?

**Comment by unbewusst** [comment]
2017-01-28 11:58 GMT+01:00 Konstantin Nesterov <notifications@github.com>:

> xlink:href



No, it doesn't work :
Failed to compile.

Error in ./src/App.js
Module build failed: TypeError: name.toLowerCase is not a function
    at Array.forEach (native)
 @ ./src/index.js 7:11-27


only one line changed in the code:
let icon = <svg viewBox="0 0 100 100" className={iconClass}><use
xlink:href="icons/sprite.svg#websocket"></use></svg>;
_______________________________________________________^^^^^^^^^_____________________________________

to resume :
xlink:href (as in normal SVG) raises the above error ;
xlinkHref (as when using ReactJS) the resulting HTML is xlinkHref not seen
by any browser ;
href         (as allowed by latest Firefox Dev Ed) pass thru in the
resulting HTML but only works on latest firefox Dev Ed.


best

Yvon

**Comment by wasd171** [comment]
That is really strange, this code works fine in tests. Might be something about create-inferno-app. However, the latest `inferno` build from `dev` branch works with `xlinkHref`, so if you need it ASAP you can pull it and build yourself, unless we publish a new release.

**Comment by Havunen** [comment]
This is bug in eslint-plugin

**Comment by unbewusst** [comment]
Ok thanks for your help, i can wait because "href" is working on Firefox
Dev Ed...


2017-01-29 10:46 GMT+01:00 Sampo Kivistö <notifications@github.com>:

**Comment by Havunen** [comment]
I have updated inferno-eslint-plugin to `6.9.2` it now has support for name spaced attributes. Closing :)

**Comment by unbewusst** [comment]
thanks a lot, works great !


2017-01-29 19:23 GMT+01:00 Sampo Kivistö <notifications@github.com>:
