### ISSUE TITLE
deploy contains readable source code

### ISSUE THREAD

**Issue by flieks** [infernojs/create-inferno-app#25]
Hi,

After `npm run build` and `firebase deploy` i can still read the source (full variable names) in dev tools. 
I need to install some extra webpack plugin?

Thanks
Greetings

**Comment by Havunen** [comment]
Hi @flieks thanks for reporting this issue. Can you check is that main file minimized or is it because you have sourcemaps there `.js.map` ?

**Comment by flieks** [comment]
Hi @Havunen i removed the .js.map from the build folder and ran firebase deploy again but after hard refresh (Ctrl+F5) in browser, the sourcemaps are still there

**Comment by flieks** [comment]
Sorry you are right, i did a new npm run build and removed .js.map from the folder. They firebase deploy did remove the source maps. Thanks alot
