### ISSUE TITLE
Alias react to inferno-compat

### ISSUE THREAD

**Issue by degroote22** [infernojs/create-inferno-app#26]
How about adding this option to the webpack config?
I'm currently ejecting just for this.
It'd be done the same way CRA treats react-native-web.
It's alised but not installed, then the user would have to install inferno-compat to use it but not worry about aliasing.
Inferno-compat is awesome and it makes styled-components, recompose, react-list, rheostat, react-share, react-sizeme work nicely for me.

**Comment by andriijas** [comment]
I agree, maybe the `create-inferno-app` command could take params to include inferno-router and compat.

**Comment by degroote22** [comment]
Including inferno router isn't necessary as it is out of the scope of this application. What I'm proposing is also not the addition of inferno-compat but just the aliasing of React.
It's what's done at this line in create-react-app: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L95
