### ISSUE TITLE
Yarn dependency

### ISSUE THREAD

**Issue by viniciusCamargo** [infernojs/create-inferno-app#28]
Hey, folks! It's my first time trying Inferno and it seems really promising. Thank you for that! 😄

I've installed create-inferno-app but I couldn't npm start it because it depends on yarn (?). I haven't found this requirement anywhere in the main readme though. It is working as expected as I installed Yarn, so it's just a heads up. 😄

**Comment by degroote22** [comment]
Could you tell us what was the error provided by npm?

**Comment by viniciusCamargo** [comment]
Hmm I'm not sure. It's on my personal laptop so I'll check if there's any log left behind when I get home.

**Comment by degroote22** [comment]
The code check the existance of a yarn.lock file to determine whether to use yarn or not. Can you confirm that this file was created by create-inferno-app?

**Comment by viniciusCamargo** [comment]
Sorry @degroote22 but I couldn't find any log. I've probably removed the directory and reinstalled the package after installing Yarn. Sorry.

**Comment by LukeSheard** [comment]
There shouldn't be any issue with yarn here, although if you can get your hands on the log that would be really useful.

**Comment by viniciusCamargo** [comment]
Sorry guys, I've uninstalled yarn and create-inferno-app and took the same steps that led me to those errors but this time everything worked as expected. Maybe there's something cached from the previous install... I don't really know. You can close this issue if you want to. 👍 I should have saved the log. 😒
