### ISSUE TITLE
Eject doesn't work

### ISSUE THREAD

**Issue by dbismut** [infernojs/create-inferno-app#31]
I realized that `yarn run eject` throws the following error in the console:

```
(node:21537) UnhandledPromiseRejectionWarning:
Unhandled promise rejection (rejection id: 1):
Error: ENOENT: no such file or directory, open
'/Users/david/repos/test-inferno/node_modules/inferno-scripts/.babelrc'
(node:21537) DeprecationWarning: Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code
```

**Comment by Havunen** [comment]
Looks like babelrc should be renamed to .babelrc

**Comment by dbismut** [comment]
Well the .babelrc file had been renamed to babelrc in one of the commits from create-react-app. In any case I just found out that this is indeed a bug in create-react-app. See here https://github.com/facebookincubator/create-react-app/issues/1806#issuecomment-286143470

**Comment by gaearon** [comment]
FYI: I don’t recommend tracking `master` of Create React App and releasing it in forks. Master is never ready. It is much safer to apply your changes on top of the latest stable release.

**Comment by Havunen** [comment]
Okay, thanks for Info @gaearon

**Comment by gaearon** [comment]
Yea, sorry about it. I guess it’s not super intuitive. If you have suggestions on how we could do this better please raise an issue.
