### ISSUE TITLE
remote-tracking the stable branch?

### ISSUE THREAD

**Issue by dbismut** [infernojs/create-inferno-app#32]
Following https://github.com/infernojs/create-inferno-app/issues/31#issuecomment-286157896, shouldn't this repo track v0.9.x of create-react-app instead of the master?

**Comment by Havunen** [comment]
Yeah, thats true. Lets change this after their next major release. That way its easier to merge (only forward no backwards).

**Comment by Havunen** [comment]
Tracking main branch now
