### ISSUE TITLE
host to Github Pages

### ISSUE THREAD

**Issue by corbane** [infernojs/create-inferno-app#33]
Hello !

I test Inferno and create-inferno-app on github pages
https://corbane.github.io/Mainstenant/

But the paths begin at the root of github...
Did I forget something?

thank you!

**Comment by LukeSheard** [comment]
It's because you've running the page on a sub-route of corbane.github.io/Mainstenant/, if you check the html tag it's trying to read a root url `/static/....` my suggestion would be use an exact url `http://corbane.github.io/Mainstenant/static/....` !
