### ISSUE TITLE
Proxy doesnt work, after ejecting

### ISSUE THREAD

**Issue by sebastianrothe** [infernojs/create-inferno-app#35]
I switched my App to the new version with Inferno 1.4 and Webpack2., but the request to the API are not proxied anymore in development. I have found the corresponding issue in one of the dependant packages: https://github.com/chimurai/http-proxy-middleware/issues/143

As suggested there, if I change config/webpackDevServer.config.js and add this line
```
https: protocol === 'https' ? {
      spdy: {
        protocols: ['http/1.1'],
      },
    } : false,
```

it works again. Can we add this line or make adjustments in scripts/addWebpackMiddleware.js ?

**Comment by Havunen** [comment]
Can you send PR for this pls :)

**Comment by sebastianrothe** [comment]
yep, on it

**Comment by sebastianrothe** [comment]
Sorry my bad. I dit not understand this completely. I was trying to proxy an http server, while the devServer was using https. If i use http for both it works. The snippet above and the issue I referenced was about websockets and proxying them.
