### ISSUE TITLE
Error: Inferno Error: Only one child is allowed within the `Provider` component

### ISSUE THREAD

**Issue by unsafecode** [infernojs/create-inferno-app#36]
As mentioned in this related issue (https://github.com/infernojs/inferno/issues/973), upgrading to `inferno@1.5.3` (which happens automatically, since the outputted `package.json` refers to `"inferno": "^x.y.z"`) produces the aforementioned error.

Solution should be updating `babel-plugin-inferno` to v3.1.0, as pointed out by @kirill-kruchkov

**Comment by Havunen** [comment]
Will do today.

**Comment by Havunen** [comment]
New versions has been released.

**Comment by Paratron** [comment]
I just checked an inferno app out from my git repository on a new machine and now have the same error. You said new versions have been released, what should I do to make it work again?
