### ISSUE TITLE
DOS line endings in the npm package files

### ISSUE THREAD

**Issue by jeffsilva** [infernojs/create-inferno-app#38]
The scrips only work on linux after i do a dos2unix on them.
Fedora 25
npm 3.10.10
node v6.10.0

**Comment by Havunen** [comment]
Sounds like bug

**Comment by MiLk** [comment]
Same on macOS 10.11.6 with node v6.10.1

**Comment by Havunen** [comment]
I can look into this today

**Comment by Havunen** [comment]
Published new version, it should work now.
