### ISSUE TITLE
Cannot find module 'react-dev-utils/clearConsole

### ISSUE THREAD

**Issue by p-adams** [infernojs/create-inferno-app#4]
Following the installation steps in the README, I create a new project `create-inferno-app`, then I run it `npm start` and I get this error:

    module.js:471
    throw err;
    ^

    Error: Cannot find module 'react-dev-utils/clearConsole'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\paadams\meow\node_modules\inferno-scripts\scripts    \start.js:26:20)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)

        npm ERR! Windows_NT 10.0.10586
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\paadams\\AppData\\Roaming \\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
       npm ERR! node v6.9.1
       npm ERR! npm  v3.10.6
       npm ERR! code ELIFECYCLE
       npm ERR! meow@0.1.0 start: `inferno-scripts start`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the meow@0.1.0 start script 'inferno-scripts start'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the meow package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     inferno-scripts start
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs meow
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls meow
       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:
       npm ERR!     C:\Users\paadams\meow\npm-debug.log`

**Comment by busypeoples** [comment]
Yes, I get the same error.

**Comment by madlotus** [comment]
`npm install --save-dev react-dev-utils`

solves the issue

**Comment by trueadm** [comment]
@madlotus that's great to hear – have you experienced any other issues with it since doing that?

**Comment by busypeoples** [comment]
@trueadm After manually installing react-dev-utils everything works fine. But do we need this dependency for inferno to work?

**Comment by trueadm** [comment]
@busypeoples I can bake this into `create-inferno-app`, it's only a `dev` overhead and shouldn't affect production.

**Comment by nilz3ro** [comment]
@trueadm Sorry about that, I removed that from packages/inferno-scripts/package.json while debugging the `eject` script.

**Comment by trueadm** [comment]
@nilz3ro No problem. Would you mind re-adding it in a PR?

**Comment by nilz3ro** [comment]
@trueadm Working on it right now, I also found a better solution to the module resolution issues in inferno-scripts/scripts/eject. PR incoming :sparkles:

**Comment by azmul** [comment]
Remove node modules. Again run npm install. Then this error will be removed.
