### ISSUE TITLE
enzyme needs react, react-dom and react-addons-test-utils

### ISSUE THREAD

**Issue by KhaledElAnsari** [infernojs/create-inferno-app#44]
Enzyme didn't work without `react`, `react-dom` and `react-addons-test-utils`! I thought `inferno-test-utils` will do the trick but it didn't

can you guys suggest anything? because I think using react and react-dom is an overkill !!

**Comment by Havunen** [comment]
Somebody should port enzyme, maybe you could?

**Comment by Havunen** [comment]
@garrensmith is working on this. https://github.com/infernojs/inferno/issues/892
