### ISSUE TITLE
eslint-config-inferno-app img-has-alt rule

### ISSUE THREAD

**Issue by IgnusG** [infernojs/create-inferno-app#45]
The jsx-a11y's `img-has-alt` rule has been modified to `alt-text` in [version 5.0.0](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v5.0.0).

**Comment by Havunen** [comment]
Hi, thanks for raising issue. Can you send PR to fix it? :)

**Comment by IgnusG** [comment]
@Havunen I'll have a look at it

**Comment by IgnusG** [comment]
https://github.com/infernojs/create-inferno-app/pull/46

**Comment by FQ400** [comment]
@Havunen when do you plan to release the changes?

**Comment by Havunen** [comment]
Released new version, branched from react.
