### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by lbssousa** [infernojs/create-inferno-app#48]
Latest create-react-app releases now build a PWA by default. I wonder if you could port this feature to create-inferno-app.

**Comment by sebastianrothe** [comment]
Is someone already doing a merge with the current version of CRA ?https://github.com/facebookincubator/create-react-app/releases/tag/v1.0.7

**Comment by LukeSheard** [comment]
@sebastianrothe Happy to take PRs for a merge from CRA!

**Comment by Havunen** [comment]
I will do fresh merge today

**Comment by Havunen** [comment]
Updated.
