### ISSUE TITLE
"Adding Bootstrap" link dead

### ISSUE THREAD

**Issue by garyrob** [infernojs/create-inferno-app#49]
The Table Of Contents has an entry for "Adding Bootstrap". When you click it, nothing happens. It appears that the anchor for that entry is simply missing. If you click the sub-entry "Using A Custom Thing" you arrive at a section with that title; above it is some text relating to "Inferno Bootstrap" but it appears inside the section "Global Variables". 

So it appears that the anchor and some of the text relating to "Inferno Bootstrap" may have gotten accidentally deleted in an edit of the page.

**Comment by Havunen** [comment]
I changed user guide links to point upstream React.
