### ISSUE TITLE
inferno-dev-utils/inquirer.js:12

### ISSUE THREAD

**Issue by jcperez-ch** [infernojs/create-inferno-app#50]
I tried to run any of the scripts:

`start`, `eject` and it was telling me that inquirer.prompt was not a function.  Then I dig a bit deeper and I found that we were requiring from the wrong module location:

```js
var inquirer = require('./inquirer');
```
instead of
```js
var inquirer = require('inquirer');
```

I tried again `yarn start` and all worked again...

**Comment by LukeSheard** [comment]
Merged #51
