### ISSUE TITLE
Testing react-based components

### ISSUE THREAD

**Issue by unsafecode** [infernojs/create-inferno-app#54]
Linking to https://github.com/infernojs/inferno/issues/1174

**Observed Behaviour**

When testing components that reference `react`-based components (like `react-bootstrap` ones), Jest reports `Cannot find module 'react' from <whatever>`. It looks like `inferno-compat` is not taken into account when testing.

Additionally, trying to _patch_ Jest configuration in `package.json` like described for Preact (https://github.com/developit/preact/issues/560) yields the following error:

![image](https://user-images.githubusercontent.com/1794924/28500094-3d9ddd62-6fc3-11e7-9b03-313a61499445.png).

Therefore, I'd say it is __not__ possible to test any react-based component today, unless ejecting from the standard config - which is, IMHO, quite disappointing for such a common scenario.

**Expected Current Behaviour**

Inferno-compat should support testing as well.

**Inferno Metadata**

Windows 10 v1703
Node@8.1.4
npm@5.3.0
inferno@3.7.0

**Comment by unsafecode** [comment]
IMHO, `createJestConfig` should be patched (https://github.com/infernojs/create-inferno-app/blob/master/packages/inferno-scripts/utils/createJestConfig.js#L34) to account for `inferno-compat` when installed.

**Comment by Havunen** [comment]
This will be fixed in todays release.
