### ISSUE TITLE
Question: migration from a React app bootstrapped with create-react-app and Typescript

### ISSUE THREAD

**Issue by benediktg** [infernojs/create-inferno-app#55]
I have a React app which I have bootstrapped with 
```
create-react-app --scripts-version=react-scripts-ts
```
and would like to see how well it performs with Inferno. (Which means: I am using Typescript but have no webpack config because it is already provided by the Typescript version of react-scripts).

Is there a simple way to do that migration?

**Comment by Havunen** [comment]
Currently typescript internally compiles everything into `createElement` calls, there is Inferno package to support that. https://www.npmjs.com/package/inferno-create-element Basically you just need to alias the React to inferno.

We also have plans for building our own typescript transformer. https://github.com/infernojs/inferno/issues/1154

createElement calls add overhead to inferno as createElement is isomorphic, when used with babel plugin all JSX is compiled into createVNode's which is the lowest level input inferno can use. The logic for compiling vNodes is done build time and not runtime (createElement).

Well that is how it works, then about the question how to make it work with given build system without access to configs I dont know :/

**Comment by benediktg** [comment]
Maybe I have to `yarn eject` so that I can modify the webpack config etc.

**Comment by Razican** [comment]
Inferno now has its own typescript transformer, right? It would be nice if create-inferno-app allowed creating an application with typescript and JSX by default.

**Comment by Havunen** [comment]
I will add 'ts-plugin-inferno' to the typescript template in the next release. Closing.
