### ISSUE TITLE
Is this supposed to read "React"?

### ISSUE THREAD

**Issue by JobLeonard** [infernojs/create-inferno-app#57]
This passage in the readme file has me a bit confused:
 
> Usage with Inferno (through inferno-compat)
> ===
> You can use Inferno components with `create-inferno-app`. All you have is to do is install `inferno-compat` (`npm install --save inferno-compat`) and Inferno and InfernoDOM will be already aliased to inferno-compat. After installing it you can import any Inferno dependent library or use any code that imports Inferno and that should work fine.

Why wouldn't `create-inferno-app` work with Inferno out of the box, and isn't `inferno-compat` meant for _React?_

Is this the result of an overzealous find/replace or am I missing something?

**Comment by Havunen** [comment]
```quote
Is this the result of an overzealous find/replace or am I missing something?
```
Yeah, I think its just documentation error.

**Comment by rendall** [comment]
I almost skipped this library because of that statement.  'inferno-compat'? I thought.  'Won't that slow down the app?'

**Comment by Havunen** [comment]
I fixed the doc.
