### ISSUE TITLE
 inferno-router props.children is Empty 

### ISSUE THREAD

**Issue by Khangeldy** [infernojs/create-inferno-app#60]
In development everything works correct. But when i deployed my app into github pages. I get error cause `this.props.children` is empty. [See Open dev console output](http://khangeldy.github.io/latin-not-hot). What i am doing wrong? 

Root.js
```javascript
const routes = (
  <Router history={browserHistory}>
    <Route component={App}>
      <IndexRoute component={Home}/>
      <Route path="/about" component={About}/>
    </Route>
  </Router>
)
```
App.js
```javascript
<div className="App-intro">
  { console.log(this.props, this.props.children)}
  { Inferno.cloneVNode(this.props.children, {diffMode: this.state.activateDiffMode}) }
</div>
```

**Comment by LukeSheard** [comment]
I think you might need to add the `path="/"` prop to your `App` `Route` component.

**Comment by Khangeldy** [comment]
Error is a chilren property. It is empty. In above code `cloneVnode` first parameter get null type. I think this problem related to github SPA pages. I solved error by changing browserHistory to hashHistory. And error only reproduced in github pages. 

```javascript
"dependencies": {
    "gh-pages": "^1.1.0",
    "inferno": "^3.10.1",
    "inferno-component": "^3.10.1",
    "inferno-router": "^3.10.1",
    "inferno-scripts": "5.0.0"
  },
```
![screenshot from 2018-01-01 14-34-26](https://user-images.githubusercontent.com/8553348/34466538-b33f362a-ef01-11e7-96b0-ea33c4b00567.png)

**Comment by Havunen** [comment]
Closing this old issue.
