### ISSUE TITLE
IE11 Syntax Error

### ISSUE THREAD

**Issue by andrewlphilpott** [infernojs/create-inferno-app#61]
I'm probably just missing something, but I just tried running a new app created with `create-inferno-app` in IE11 and I'm getting a syntax error. It looks like it’s because of the arrow function in `inferno-dev-utils/node_modules/ansi-regex/index.js`:

```
module.exports = () => {
	const pattern = [
		'[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[a-zA-Z\\d]*)*)?\\u0007)',
		'(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PRZcf-ntqry=><~]))'
	].join('|');

	return new RegExp(pattern, 'g');
};
```

Do I need to add a polyfill or something to get this to work in IE11?

**Comment by Havunen** [comment]
hmm, that seems to be third party module, used only in development.

**Comment by andrewlphilpott** [comment]
I assume so, but I haven't tried running it yet.

**Comment by andrewlphilpott** [comment]
@Havunen Yep, the production build is fine. Probably not a huge deal since it's just development but it may make browser testing a little more cumbersome for anybody needing to support IE11 and down.

**Comment by Havunen** [comment]
Maybe we should refactor that third party out of this library?

**Comment by LukeSheard** [comment]
@andrewlphilpott I could imagine that it’s due to a webpack config setting that means node modules aren’t processed by Babel in development but are in production.

**Comment by farooqkz** [comment]
As IE has been obsolete, I think this issue is not valid anymore.

**Comment by Havunen** [comment]
IE11 is not officially supported anymore.

**Comment by farooqkz** [comment]
@Havunen You had to close it as invalid
