### ISSUE TITLE
Use jsx-uses-inferno eslint rule

### ISSUE THREAD

**Issue by jstrangfeld** [infernojs/create-inferno-app#62]
`eslint-plugin-inferno` provides better eslint rules than the default configuration. In particular, eslint gives the following warning with every component: `'Inferno' is defined but never used  (no-unused-vars)`

There are two solutions:

1) Use .eslintrc configuration from the project root, if present. Currently, custom .eslintrc files are ignored. Allow developers to customize eslint using their own configuration.

2) Add `eslint-plugin-inferno` as a project dependency and configure eslint to use it automatically. This would change the default rules for everyone without giving an option to modify them.

**Comment by Havunen** [comment]
Hi @jstrangfeld can you send PR for this?

**Comment by jstrangfeld** [comment]
I dug into this more and it looks like the rule I am requesting is not enabled by default. I will submit a pull request.

**Comment by Havunen** [comment]
Wait a minute, I might have misunderstood something here. This error is valid: 
```'Inferno' is defined but never used (no-unused-vars)```
because after v4 babel plugin can import what it needs and you dont need `import Inferno from 'inferno'`

**Comment by jstrangfeld** [comment]
Closed in #63
