### ISSUE TITLE
Unclear usage/install instructions

### ISSUE THREAD

**Issue by kristianmandrup** [infernojs/create-inferno-app#64]
You demonstrate usage using the `npx` binary.

I assume you mean [npx](https://www.npmjs.com/package/npx) which I had never heard about before. Ah, I see a link on the Readme to this [blog post](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) but had to really look for it...

Please provide better usage instructions, including using the `create-inferno-app` binary directly without `npx`. Thanks :)

**Comment by Havunen** [comment]
npx is native program since npm 5.2+ There are instructions on Readme how to use it on older npm version. Also updated websites. https://infernojs.org/docs/guides/installation
