### ISSUE TITLE
Environment variables typos

### ISSUE THREAD

**Issue by andrewlphilpott** [infernojs/create-inferno-app#65]
The [documentation for environment variables](https://github.com/infernojs/create-inferno-app/blob/master/packages/inferno-scripts/template/README.md#adding-development-environment-variables-in-env) mentions that you need to prepend variable names with `REACT_APP_`, but it looks like the actual prefix is `INFERNO_APP_`. The incorrect prefix is mentioned several times in the doc.

**Comment by Havunen** [comment]
Thats true... It would be awesome if you can send PR to fix it.
