### ISSUE TITLE
Basic usage not working

### ISSUE THREAD

**Issue by steodor** [infernojs/create-inferno-app#67]
Hi, i tried creating an inferno app using this tool but it's generating a broken app.

**Environment:**
- Windows 10
- Chrome 65.0.3325.125 (latest at this time)
- node v9.8.0
- npm v5.7.1
- npx v9.7.1

**Steps:**
1. `npx create-inferno-app test`
2. `cd test`
3. `npm start`

**Expected behavior:** `localhost:3000` should load a working inferno-based app
**Actual behavior:** the local server starts fine, but delivers an app which renders nothing and crashes with the following error:

```
Uncaught TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (index.js:72)
    at Object../node_modules/inferno-dev-utils/node_modules/chalk/index.js (index.js:228)
...
```

Here's a screenshot of the error: https://www.screencast.com/t/ghJsLdwMr8UG

Please advise :)
Thank you for your time!

**Comment by Havunen** [comment]
Strange, I cannot reproduce this in Windows / Linux

**Comment by steodor** [comment]
Maybe it's environment-specific. I suggest closing it after a while if nobody else reports having the same issue. Thank you.

**Comment by Havunen** [comment]
The next major version will require Node 20 or newer.
