### ISSUE TITLE
Create-Inferno-App failing install with Node v.10 due to upath@1.0.4

### ISSUE THREAD

**Issue by jmhdev** [infernojs/create-inferno-app#69]
I receive the following error message when using create-inferno-app after install new Node version:

yarn add v1.6.0
(node:29860) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.2: The platform "win32" is incompatible with this module.
info "fsevents@1.2.2" is an optional dependency and failed compatibility check. Excluding it from installation.
**error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module**
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.

I haven't had a chance to figure out which package is depending on upath version 1.0.4  and causing this error.

Edit:  This is not isolated to create-inferno-app, same issue exists with create-react-app (not suprising)

**Comment by zolodeveloper** [comment]
> Filed this same issue with create-react-app, got a quick fix response from @retyui:
> 
> > Small fix
> > `yarn config set ignore-engines true`

it worked

**Comment by Havunen** [comment]
I have rebased all updates from the upstream, updated all the depencies to latest versions and converted the source code to ESM.
The next major version will require Node 20 or newer.
