### ISSUE TITLE
README.md - User guide

### ISSUE THREAD

**Issue by asantos00** [infernojs/create-inferno-app#7]
Hi!

I've noticed that User Guide's links on README.md are pointing do `facebookincubator`. I don't know if somebody has already noticed that, but I can obviously do it in a PR if you guys want.

Good job with inferno :)

**Comment by trueadm** [comment]
@asantos00 that would be awesome thanks! :)

**Comment by asantos00** [comment]
Done here :)

https://github.com/infernojs/create-inferno-app/pull/8/files
