### ISSUE TITLE
.env variables not present in process.env

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [infernojs/create-inferno-app#71]
**my `.env` file**

```
HOST = pwa.w88.local
PUBLIC_URL = /pwa
SESSION_POLLING_TIMEOUT = 30
```

**my `src/index.js` file**

```js
console.log(process.env);
```

**I only see**

```js
{NODE_ENV: "development", PUBLIC_URL: ""}
```

**I should see**

my defined variable, `SESSION_POLLING_TIMEOUT` and `PUBLIC_URL` available there.

**Comment by sprlwrksAprilmintacpineda** [comment]
solution: prefix the variables with `INFERNO_APP_` then it's available as `process.env.INFERNO_APP_VARNAME`. Can this be overridden? I don't want every variables to have `INFERNO_APP_` in their name.

**Comment by Havunen** [comment]
The scripts use webpack under the hood. Are you familiar with webpack? Maybe you could try fix this?

**Comment by sprlwrksAprilmintacpineda** [comment]
@Havunen  Hmmm, maybe I can if I can find that part, I don't even know where the webpack configs are...

**Comment by Havunen** [comment]
This is how it was designed to work. Closing this issue. All customn env vars needs to go under INFERNO_APP just like for React its REACT_APP
