### ISSUE TITLE
My function call transpiled to (void, 0)

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [infernojs/create-inferno-app#77]
## From

![image](https://user-images.githubusercontent.com/39720421/46133999-6f0e4080-c274-11e8-8b49-16d984fcc2c9.png)

## To

![image](https://user-images.githubusercontent.com/39720421/46134040-8b11e200-c274-11e8-97fe-f302853554b3.png)

It happens when I do this:

```js
if (!cookie || cookie < Date.now()) {
    function isPortrait () {
      // .. codes
    }

    function displayCorrectSplashImage () {
      // .. codes
    }

    // ... rest of the codes
}
```

Notice the `displayCorrectSplashImage` function, that's the one with the issue. If I move it out of the if statement like so:

```js
function isPortrait () {
  // .. codes
}

function displayCorrectSplashImage () {
  // .. codes
}

if (!cookie || cookie < Date.now()) {
    // ... rest of the codes
}
```

It then transpiles into this:

![image](https://user-images.githubusercontent.com/39720421/46135478-e0032780-c277-11e8-9804-46254bef9700.png)

Which is the working one.

**Comment by sprlwrksAprilmintacpineda** [comment]
@Havunen I'm not sure if this is a problem with inferno-script or tools that it uses.

**Comment by Havunen** [comment]
I have rebased all updates from the upstream, updated all the depencies to latest versions and converted the source code to ESM.
The next major version will require Node 20 or newer.

This issue will most likely be fixed after upgrading one of these dependencies. Closing.
