### ISSUE TITLE
How do I use Linaria or Astroturf with this webpack setup?

### ISSUE THREAD

**Issue by tamb** [infernojs/create-inferno-app#81]
I've ejected and I can't seem to figure out how to add either of these CSS-in-JS libraries
https://github.com/callstack/linaria
https://github.com/4Catalyzer/astroturf

I keep getting issues with the `css` tag not being supported and that the babel loaders are not set up correctly.  Could someone paste an example of how to actually set one of these up?

**Comment by Havunen** [comment]
This repository has gone over a huge update. Im closing this as the scripts have changed.
