### ISSUE TITLE
Pretty far behind the fork of create-react-app

### ISSUE THREAD

**Issue by tamb** [infernojs/create-inferno-app#82]
For starters, ejecting the app shows that the webpack configs are way too separate.  If I need an alias I have to write it in 2 files or create a new file and import it into both files.  This is a no go.

**Comment by Havunen** [comment]
@tamb would you like to create PR for latest changes? There is not many differences between Inferno and React. I'm traveling currently, I can look into this in month time frame If you cant :)

**Comment by tamb** [comment]
@Havunen Should that be done with a fork of create-react-app or a fork of this?  What's the better way to approach it?

**Comment by Havunen** [comment]
Good question. Usually I have just merged latest changes from React side here. Doing a merge commit.

Fork this repo. Add this as another remote. Add React as another remote. Then merge from React to your repo and open PR.

**Comment by Havunen** [comment]
There might be better ways to do it, but thats what I have done

**Comment by tamb** [comment]
Cool.  I'll try to get on that approach and make a pr in my spare time.

**Comment by Havunen** [comment]
I will create new fork of inferno-eslint-plugin and then try to get this repo updated. Hopefully tomorrow

**Comment by Havunen** [comment]
eslint-plugin-inferno is now up to date, and way faster than before :) 
next we need to get this repo up to date.

**Comment by Havunen** [comment]
@tamb Have you started the fork? How did it go?

**Comment by Razican** [comment]
Is there news in this regard?

**Comment by tamb** [comment]
I have not started the fork.  It was a long process. I'm sorry.  I let the Inferno Team down

**Comment by Razican** [comment]
@tamb don't worry. Nobody else did it as far as it seems. It would be great to have it now. I wouldn't know where to start though.

**Comment by Havunen** [comment]
I have rebased all updates from the upstream, updated all the depencies to latest versions and converted the source code to ESM.
The next major version will require Node 20 or newer.
