### ISSUE TITLE
Inferno compat question

### ISSUE THREAD

**Issue by arjunmehta94** [infernojs/create-inferno-app#83]
i'm facing a pretty basic problem with rendering react components.

I'm trying to use a [react component](https://github.com/react-component/color-picker) in my create-inferno-app app. I installed the inferno-compat library and am able to successfully import the react component but it never seems to render (div has 0 height on inspection). Not sure if I'm missing a step here

**Comment by arjunmehta94** [comment]
<img width="219" alt="Screen Shot 2020-06-27 at 4 42 01 PM" src="https://user-images.githubusercontent.com/5506399/85934237-33fbcf80-b895-11ea-9200-3f220f0da88c.png">
<img width="790" alt="Screen Shot 2020-06-27 at 4 41 45 PM" src="https://user-images.githubusercontent.com/5506399/85934238-33fbcf80-b895-11ea-9aad-cb2cdea50421.png">

**Comment by arjunmehta94** [comment]
I'm importing the component like
```
import ColorPicker from 'rc-color-picker';
```

and then using it in the render component like
```
render() {
 //...
 <ColorPicker />
}
```

**Comment by Havunen** [comment]
Hi,

Have you tried does that component work in latest version of React? 
There can be so many reasons why this fails, it needs more information. Somebody needs to debug what is different.
