### ISSUE TITLE
Fails trying to install inferno-scripts

### ISSUE THREAD

**Issue by mirkonasato** [infernojs/create-inferno-app#9]
Creating an app fails:

```
$ create-inferno-app my-app
...
npm ERR! argv "/Users/mirko/.nvm/versions/node/v7.2.1/bin/node" "/Users/mirko/.nvm/versions/node/v7.2.1/bin/npm" "install" "--save-dev" "--save-exact" "inferno-scripts"
npm ERR! Path must be a string. Received undefined
```

Same happens trying to install `inferno-scripts` manually:

```
my-app$ npm install --save inferno-scripts
npm ERR! argv "/Users/mirko/.nvm/versions/node/v7.2.1/bin/node" "/Users/mirko/.nvm/versions/node/v7.2.1/bin/npm" "install" "--save" "inferno-scripts"
npm ERR! Path must be a string. Received undefined
```

Latest available inferno-scripts version:
```
$ npm view inferno-scripts version
0.7.10
```

### Environment

```
System Version: macOS 10.12.1
$ node -v
v7.2.1
$ npm -v
4.0.3
```

**Comment by mirkonasato** [comment]
Is this the right repo, or is it [facebookincubator/create-react-app](https://github.com/facebookincubator/create-react-app)?

The [trueadm/inferno readme](https://github.com/trueadm/inferno#getting-started) points to this one.

**Comment by nilz3ro** [comment]
@mirkonasato I'm able to reproduce this issue with node v7.2.1 and npm 4.0.3, thanks for filing an issue for this.

**Comment by mirkonasato** [comment]
Same with Node 6.9 and npm 3 by the way.

**Comment by nilz3ro** [comment]
@mirkonasato That leads me to believe it's a problem with the package and not a compatibility issue. Fortunately there's a helpful argument error to point us in the right direction.

**Comment by Havunen** [comment]
Thanks for reporting this issue.

It has now been fixed. Closing.
