### ISSUE TITLE
Dependencies must be upgraded

### ISSUE THREAD

**Issue by farooqkz** [infernojs/create-inferno-app#90]
CIA uses several important dependencies which have newer versions. Some like webpack must be upgraded to 5.x before 4.x gets deprecated. Some like babel related stuff already have been deprecated or their packages habe been moved on npm.

**Comment by farooqkz** [comment]
I will write things which are deprecated(might be incomplete). Will update this message as I find more.

Current list:

 - `eslint-loader` has been deprecated
 - `webpack` must be upgraded to 5.x
 - ...

**Comment by Havunen** [comment]
It might be easier to rebase the fork from the upstream rather than start updating dependencies here

**Comment by farooqkz** [comment]
Well I've ejected my app and I have to update dependencies myself anyway...

**Comment by farooqkz** [comment]
Related: https://github.com/infernojs/babel-plugin-inferno/issues/62

@Havunen thoughts?

**Comment by farooqkz** [comment]
@Havunen What about a note in README.md saying that for new apps, CIA must not be used?

**Comment by EM-LilianaIturribarria** [comment]
is something still maintaining this?
i also found the same issue... or is there an alternative to use?

**Comment by Havunen** [comment]
I have rebased all updates from the upstream, updated all the depencies to latest versions and converted the source code to ESM.
The next major version will require Node 20 or newer.

**Comment by EM-LilianaIturribarria** [comment]
thank you so much @Havunen !!
