### ISSUE TITLE
create-inferno-app dependency issue

### ISSUE THREAD

**Issue by patrickspiegel** [infernojs/create-inferno-app#91]
babel-eslint installs a different eslint version preventing starting new projects. No special steps are required to reproduce. 
```
└─┬ inferno-scripts@7.0.4
  ├─┬ babel-eslint@10.0.1
  │ └─┬ eslint@8.36.0
  │   └─┬ @eslint-community/eslint-utils@4.2.0
  │     └── eslint@8.36.0 deduped
  ├─┬ eslint-config-inferno-app@7.0.2
  │ └── eslint@5.9.0 deduped
  ├─┬ eslint-loader@2.1.1
  │ └── eslint@5.9.0 deduped
  ├─┬ eslint-plugin-flowtype@3.2.0
  │ └── eslint@8.36.0 deduped
  ├─┬ eslint-plugin-import@2.14.0
  │ └── eslint@5.9.0 deduped
  ├─┬ eslint-plugin-inferno@7.32.1
  ├─┬ eslint-plugin-jsx-a11y@6.1.2
  │ └── eslint@5.9.0 deduped
  └── eslint@5.9.0
```

**Comment by EM-LilianaIturribarria** [comment]
Anyone taking a look at this issue?

i have some dependencies issue as well, What node/npm version should we use for create-inferno-app?
dev dependencies are old, any planning to update those?

**Comment by Havunen** [comment]
I have rebased all updates from the upstream, updated all the depencies to latest versions and converted the source code to ESM.
The next major version will require Node 20 or newer.
